-- preload = /path/to/image.png
--if more than one preload is desired then continue to preload other backgrounds
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'preload = ~/.config/hypr/Wallpapers/1382317.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = ~/.config/hypr/Wallpapers/1374032.png' has no enclosing section

--set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
--if more than one monitor in use, can load a 2nd image
-- wallpaper = monitor2,/path/to/next_image.png
-- .. more monitors

-- wallpaper = eDP-1, ~/.config/hypr/Wallpapers/1382317.png
-- wallpaper = DP-1, ~/.config/hypr/Wallpapers/1382317.png
-- wallpaper =, ~/.config/hypr/Wallpapers/1374032.png

--enable splash text rendering over the wallpaper
-- TODO: manual review — top-level key 'splash = false' has no enclosing section

--fully disable ipc
-- ipc = off

