--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- env = __NV_PRIME_RENDER_OFFLOAD, 1 
-- env = LIBVA_DRIVER_NAME,nvidia
-- env = __GLX_VENDOR_LIBRARY_NAME,nvidia
-- env = LIBVA_DRIVER_NAME,nvidia
-- env = GBM_BACKEND,nvidia-drm
-- env = NVD_BACKEND,direct
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
-- TODO: manual review — malformed env on line 18: GDK_BACKEND,wayland,x11,*
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
-- env = SDL_VIDEODRIVER,xcb
-- env = WLR_NO_HARDWARE_CURSORS,1
-- env = MOZ_ENABLE_WAYLAND,1
-- env = _JAVA_AWT_WM_NONREPARENTING,1
-- env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
--
hl.env("SSH_AUTH_SOCK", "$XDG_RUNTIME_DIR/ssh-agent.socket")

--for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons   
--you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
