--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & 
-- exec-once = hyprpaper & 

-- exec = killall waybar && waybar & 
--

--for libadwaita gtk4 apps you can use this command:

--for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)

hl.on("hyprland.start", function()
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("hyprpanel &")
    hl.exec_cmd("dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user restart xdg-desktop-portal.service")
    hl.exec_cmd("sleep 1 && /usr/lib/xdg-desktop-portal-hyprland &")
    hl.exec_cmd("awww-daemon")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("awww img ~/.config/hypr/Wallpapers/violet-descent.gif")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme \"adw-gtk3\"")
end)

