--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local KEY_1 = "ampersand"
local KEY_2 = "eacute"
local KEY_3 = "quotedbl"
local KEY_4 = "apostrophe"
local KEY_5 = "parenleft"
local KEY_6 = "minus"
local KEY_7 = "egrave"
local KEY_8 = "underscore"
local KEY_9 = "ccedilla"
local KEY_0 = "agrave"
local terminal = "kitty"
local fileManager = "yazi"
local browser = "zen-browser"
local menu = "fuzzel"

hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("hyprctl reload"))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
-- bind = $mainMod, J, togglesplit, # dwindle
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("thunderbird"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("gnome-calculator"))

hl.bind(mainMod .. " + SUPER_L", hl.dsp.exec_cmd("$menu"))
hl.bind("CTRL+ALT + DELETE", hl.dsp.exec_cmd("eww open powermenu"))

hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind(mainMod .. " + ALT+SHIFT + W", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. KEY_1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. KEY_2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. KEY_3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. KEY_4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. KEY_5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. KEY_6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. KEY_7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. KEY_8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. KEY_9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. KEY_0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + " .. KEY_1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + " .. KEY_0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse_right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_left", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + SHIFT + page_up", hl.dsp.window.move({ workspace = "+1" }))
hl.bind(mainMod .. " + SHIFT + page_down", hl.dsp.window.move({ workspace = -1 }))
hl.bind(mainMod .. " + ALT + page_up", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + ALT + page_down", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + page_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + page_down", hl.dsp.focus({ workspace = -1 }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
