--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "",
	mode = "1920x1080@60.00",
	position = "auto",
	scale = "1",
})

-- monitor=DP-1,preferred,0x0,1
-- monitor=DP-2,preferred,auto,1
hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080",
	position = "auto-right",
	scale = "1",
})

-- Specific Monitors
hl.monitor({
	output = "desc:HGC CR240HD",
	mode = "1920x1080@180",
	position = "auto-right",
	scale = "1",
})

-- monitor=desc:Samsung Electric Company SAMSUNG 0x01000E00,preferred,0x-1080,1

hl.workspace_rule({
	workspace = "1",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "2",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "1",
	monitor = "DP-1",
})

hl.workspace_rule({
	workspace = "2",
	monitor = "DP-1",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "DP-1",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "DP-1",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "DP-1",
})

hl.workspace_rule({
	workspace = "6",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "7",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "8",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "9",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "10",
	monitor = "HDMI-A-1",
})

-- workspace=21,monitor:DP-2
-- workspace=22,monitor:DP-2
-- workspace=23,monitor:DP-2
-- workspace=24,monitor:DP-2
-- workspace=25,monitor:DP-2
