--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- monitor=DP-1,preferred,0x0,1
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "DP-3",
	mode = "preferred",
	position = "auto-right",
	scale = "1",
})

hl.monitor({
	output = "HDMI-A-3",
	mode = "preferred",
	position = "auto-left",
	scale = "1",
})

-- Specific Monitors
hl.monitor({
	output = "desc:HGC CR240HD",
	mode = "1920x1080@180",
	position = "auto-right",
	scale = "1",
})

-- monitor=desc:Samsung Electric Company SAMSUNG 0x01000E00,preferred,0x-1080,1

hl.workspace_rule({
	workspace = "1",
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = "2",
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = "6",
	monitor = "HDMI-A-3",
})

hl.workspace_rule({
	workspace = "7",
	monitor = "HDMI-A-3",
})

hl.workspace_rule({
	workspace = "8",
	monitor = "HDMI-A-3",
})

hl.workspace_rule({
	workspace = "9",
	monitor = "HDMI-A-3",
})

hl.workspace_rule({
	workspace = "10",
	monitor = "HDMI-A-3",
})

-- workspace=21,monitor:DP-2
-- workspace=22,monitor:DP-2
-- workspace=23,monitor:DP-2
-- workspace=24,monitor:DP-2
-- workspace=25,monitor:DP-2
