--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
-- windowrule = suppress_event maximize, match:class .*

-- Fix some dragging issues with XWayland
-- windowrule = no_focus on,  match:class .*,match:xwayland 1,match:float false,match:fullscreen 0,match:pin false 
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    opacity = "0.85 0.875",
})

--
hl.window_rule({
    match = {
        title = "(Zen Browser)",
    },
    opacity = 0.98,
})

hl.window_rule({
    match = {
        class = "Unity",
    },
    opacity = 1,
})

hl.window_rule({
    match = {
        class = "blender",
    },
    opacity = 1,
})

hl.window_rule({
    match = {
        title = "(Org.gnome.Calculator)",
    },
    float = true,
})

-- windowrule = opacity 1, class:discord

