##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
# windowrule = no_focus on,  match:class .*,match:xwayland 1,match:float false,match:fullscreen 0,match:pin false 
windowrule = opacity 0.85 0.875, match:class .* 
#
windowrule = opacity 0.98, match:title (Zen Browser)  
windowrule = opacity 1, match:class Unity
windowrule = opacity 1, match:class blender
windowrule = float on, match:title (Org.gnome.Calculator)
# windowrule = opacity 1, class:discord

